### ISSUE TITLE
Add v1 LE ssp370 meta data definition

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/CMIP6-Metadata#18]
Hey @TonyB9000, 
We will need to add corresponding ssp370_rxixpxfx.json files for v1 LE sp370 ensembles under [E3SM-1-0-LE](https://github.com/E3SM-Project/CMIP6-Metadata/tree/master/E3SM-1-0-LE). I'm listing fields (see below) that need to change between a historical and ssp370 pair. 

"experiment_id": "historical", -> "ssp370"
"activity_id": "CMIP", ->"ScenarioMIP"
"parent_experiment_id": "piControl", -> "historical"
"parent_time_units": "days since 0001-01-01", ->"days since 1850-01-01", 
"branch_time_in_parent": xxxxx, -> "60225.0"
"history": should use the original casename for each ssp370 ensemble. i.e"20191024.en1.LE_ens_1_ssp370.ne30_oECv3_ICG.compy"

Other fields should be left unchanged for each pair.

@TonyB9000 could you help to implement this?

**Comment by TonyB9000** [comment]
Yes, I can handle this.  I can use the "ncatted" tool (wrapped with my control script).

Is "branch_time_in_parent" a constant?  With the historical (20 ensembles), each ensemble had a different branch-time.

I'll get this done Friday morning, hopefully we can start Cmorizing in the afternoon!

**Comment by TonyB9000** [comment]
Correction: "ncatted" is for updating metadata in the ".nc" files.  I will be using my
"/p/user_pub/e3sm/staging/tools/update_json_value.py"

**Comment by chengzhuzhang** [comment]
@TonyB9000 Hi I'm looking at your latest commit to `master`, if i understand correctly, I think the only thing needs to be corrected is to use `_controlled_vocabulary_file` to replace `_control_vocabulary_file`.

**Comment by chengzhuzhang** [comment]
close with #19
